server:
  port: 10101

spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.url:localhost:3306}/epoch-workflow?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: marshal1234!

  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    favicon:
      enabled: true

  activiti:
    async-executor-activate: true
    mail-server-use-ssl: true
    #自动更新数据库
    database-schema-update: false
    #校验流程文件，默认校验resources下的processes文件夹里的流程文件
    check-process-definitions: false
    #restApiEnabled: false
    jpa-enabled: false

    epoch:
      table-name-upper-case: false



# mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
#  configuration:
#    jdbc-type-for-null: null

# 通用mapper配置
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: mysql

# pageHelper插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
